### ISSUE TITLE
I agree with you. Microsoft has changed.

### ISSUE THREAD

**Issue by TooYoungTooSimp** [MarounMaroun/IMMA_STAY_IF_MS_BUYS_GITHUB#2]
Microsoft has changed its attitude to opensource a lot.
We can see Visual Studio Code, dotnet, powershell and lots of other projects are opensource.
And Microsoft is one of the biggest contributor in GitHub.
I believe MS will not harm GitHub, at least now.

**Comment by WaKeMaTTa** [comment]
@TooYoungTooSimp Are you sure you don't work for Microsoft? I say this because you have his logo as avatar. :laughing:  :laughing:  :laughing:  :laughing:  :laughing:  :laughing:  :laughing:  :laughing:  :laughing:  :laughing:  :laughing:  :laughing:  :laughing:  :laughing:

**Comment by depado** [comment]
There are a lot of pro-open source people now working and advocating at Microsoft.
God knows how much I hated MS a few years back, but they have changed.
They won't change a thing in Github.

I also believe MS won't harm GitHub, at all. And it's actually a good thing. Even though I'm not a big fan of having all my eggs in the same basket (and that's why I have a gitea that has been running for a few years, mirroring my repos).

**Comment by TooYoungTooSimp** [comment]
@WaKeMaTTa hahaha, I'm just a student.
In my class pretending to be no ability is normal, so I chose a full recycle bin as my avatar. 😆
